version: '2'
services:
  viddit:
    build: .
    container_name: viddit

    #restart: always
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: always
    depends_on:
      - viddit