version: '2'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  viddit:
    build: .
    container_name: viddit

    # args:
    #   - SUBREDDITS=Showerthoughts
    #   - MAX_COMMENTS=5
    #   - MAX_VIDEOS=20
